In [9]:
# Install sweetviz if it's not already installed
!pip install sweetviz

import pandas as pd
import sweetviz as sv

# The file path needs to be accessible within the Colab environment.
# Please upload the file '2020_al_data_kaggle_upload_new_old_syllabi.csv'
# to the Colab session's root directory (/content/).
# Or, if it's in Google Drive, mount your drive and update the path accordingly.
file_path = r"/content/2020_al_data_kaggle_upload_new_old_syllabi.csv"

print("Data reading")
# Data tika read karaganna
df = pd.read_csv(file_path)

print("Report creating..")
# Profiling report eka hadanna
report = sv.analyze(df)

# HTML file eka widihata save karala auto open karanna
report.show_html(filepath="profiling_report.html", open_browser=True)
print("finished!")

Requirement already satisfied: sweetviz in /usr/local/lib/python3.13/dist-packages (2.3.3)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (2.2.3)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (2.1.3)
Requirement already satisfied: matplotlib>=3.1.3 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (3.10.0)
Requirement already satisfied: tqdm>=4.43.0 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (4.67.3)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (1.16.3)
Requirement already satisfied: jinja2>=2.11.1 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (3.1.6)
Requirement already satisfied: importlib_resources>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2>=2.11.1->sweetviz) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)
Data reading
Report creating..

                                             |          | [  0%]   00:00 -> (? left)

Report profiling_report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.
finished!

In [13]:
import pandas as pd

# Oyage file eke path eka
file_path = r"/content/2020_al_data_kaggle_upload_new_old_syllabi.csv"

# Data tika read karaganna
df = pd.read_csv(file_path)

# Rows saha Columns gana balanna
print("ROWS AND COLS (Raw and column):", df.shape)

# Thiyena columns wala nam tika balanna
print("\nCOLUMNS:")
print(df.columns.tolist())

# Data set eke mul raw 5 balanna
print("\nHEAD (Mul raw 5):")
print(df.head())

# Adu (Missing) values thiyenawada kiyala balanna
print("\nMISSING VALUES (Adu data):")
print(df.isnull().sum())

ROWS AND COLS (Raw and column): (337553, 19)

COLUMNS:
['index', 'stream', 'Zscore', 'district_rank', 'island_rank', 'al_year', 'sub1', 'sub1_r', 'sub2', 'sub2_r', 'sub3', 'sub3_r', 'cgt_r', 'ge_r', 'syllabus', 'birth_day', 'birth_month', 'birth_year', 'gender']

HEAD (Mul raw 5):
   index    stream  Zscore district_rank  island_rank  al_year  \
0      0      ARTS  -.3550    4336 (NEW)  64994 (NEW)     2020
1      1      ARTS  -.2648    4154 (NEW)  62338 (NEW)     2020
2      2  COMMERCE  -.4760    6910 (NEW)  37307 (NEW)     2020
3      3  COMMERCE  -.1012    5678 (NEW)  30449 (NEW)     2020
4      4  COMMERCE   .6014    3269 (NEW)  17010 (NEW)     2020

                sub1 sub1_r               sub2 sub2_r        sub3 sub3_r  \
0  POLITICAL SCIENCE      S  DANCING(BHARATHA)      C       TAMIL      S
1  POLITICAL SCIENCE      S     CARNATIC MUSIC      C       TAMIL      C
2          ECONOMICS      S   BUSINESS STUDIES      S  ACCOUNTING      S
3          ECONOMICS      C   BUSINESS STUDIES      C  ACCOUNTING      S
4          ECONOMICS      C   BUSINESS STUDIES      C  ACCOUNTING      B

  cgt_r ge_r syllabus birth_day birth_month birth_year  gender
0   056    S      new        31         May       2001  female
1   032    C      new        13     January       2002  female
2   050    S      new        16      August       2001  female
3   034    S      new        16      August       2001  female
4   036    S      new         7      August       2000  female

MISSING VALUES (Adu data):
index               0
stream              0
Zscore              0
district_rank       0
island_rank         0
al_year             0
sub1                0
sub1_r              0
sub2                0
sub2_r              0
sub3                0
sub3_r              0
cgt_r               0
ge_r                0
syllabus            0
birth_day           0
birth_month         0
birth_year          0
gender           1484
dtype: int64

In [14]:
df['stream'].value_counts()

stream
-                         150514
ARTS                       76547
COMMERCE                   39877
BIOLOGICAL SCIENCE         25768
PHYSICAL SCIENCE           21776
ENGINEERING TECHNOLOGY     12498
BIOSYSTEMS TECHNOLOGY       7833
NON                         2740
Name: count, dtype: int64

In [15]:
df['gender'].value_counts()

gender
female         193326
male           142719
Major error        24
Name: count, dtype: int64

In [16]:
df['cgt_r'].value_counts()

cgt_r
Absent    76628
040       16182
042       15931
038       15462
044       15135
          ...
004           2
000           2
100           1
098           1
092           1
Name: count, Length: 73, dtype: int64

First, let's clean the `district_rank` column by extracting only the numerical part and converting it to an integer. Then we can filter for ranks less than 500.

In [19]:
# Function to extract the numerical part from 'district_rank'
def extract_rank(rank_str):
    if isinstance(rank_str, str):
        try:
            return int(rank_str.split(' ')[0])
        except ValueError:  # Catch error if conversion to int fails (e.g., for '-')
            return None
    return None

# Apply the function to create a new numerical rank column
df['district_rank_numeric'] = df['district_rank'].apply(extract_rank)

# Filter the DataFrame for district_rank_numeric less than 500
df_filtered_rank = df[df['district_rank_numeric'] < 500]

print("Shape of the filtered DataFrame:", df_filtered_rank.shape)
print("\nHead of the filtered DataFrame (district_rank < 500):")
display(df_filtered_rank.head())

Shape of the filtered DataFrame: (70649, 20)

Head of the filtered DataFrame (district_rank < 500):

,index,stream,Zscore,district_rank,island_rank,al_year,sub1,sub1_r,sub2,sub2_r,sub3,sub3_r,cgt_r,ge_r,syllabus,birth_day,birth_month,birth_year,gender,district_rank_numeric
49,49,ARTS,1.9997,108 (NEW),588 (NEW),2020,ECONOMICS,A,POLITICAL SCIENCE,A,ISLAM,A,062,A,new,3,February,2001,female,108.0
139,139,COMMERCE,1.8182,373 (NEW),1246 (NEW),2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,046,B,new,24,July,2001,male,373.0
185,185,COMMERCE,1.7950,412 (NEW),1370 (NEW),2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,050,C,new,17,December,2001,male,412.0
188,188,PHYSICAL SCIENCE,2.0254,259 (NEW),922 (NEW),2020,PHYSICS,B,CHEMISTRY,A,COMBINED MATHEMATICS,A,078,B,new,30,January,2002,male,259.0
199,199,PHYSICAL SCIENCE,1.7636,419 (NEW),1805 (NEW),2020,PHYSICS,A,CHEMISTRY,A,COMBINED MATHEMATICS,B,068,A,new,9,November,2001,male,419.0

In [22]:
print('Before dropping nulls and duplicates:')
print('Shape:', df.shape)
print('Missing values in gender:', df['gender'].isnull().sum())
print('Duplicate rows:', df.duplicated().sum())

# Drop rows where 'gender' is null
df_cleaned = df.dropna(subset=['gender']).copy()

# Drop duplicate rows from the entire DataFrame
df_cleaned = df_cleaned.drop_duplicates().copy()

print('\nAfter dropping nulls and duplicates:')
print('Shape:', df_cleaned.shape)
print('Missing values in gender:', df_cleaned['gender'].isnull().sum())
print('Duplicate rows:', df_cleaned.duplicated().sum())

display(df_cleaned.head())

Before dropping nulls and duplicates:
Shape: (337553, 20)
Missing values in gender: 1484
Duplicate rows: 0

After dropping nulls and duplicates:
Shape: (336069, 20)
Missing values in gender: 0
Duplicate rows: 0

,index,stream,Zscore,district_rank,island_rank,al_year,sub1,sub1_r,sub2,sub2_r,sub3,sub3_r,cgt_r,ge_r,syllabus,birth_day,birth_month,birth_year,gender,district_rank_numeric
0,0,ARTS,-.3550,4336 (NEW),64994 (NEW),2020,POLITICAL SCIENCE,S,DANCING(BHARATHA),C,TAMIL,S,056,S,new,31,May,2001,female,4336.0
1,1,ARTS,-.2648,4154 (NEW),62338 (NEW),2020,POLITICAL SCIENCE,S,CARNATIC MUSIC,C,TAMIL,C,032,C,new,13,January,2002,female,4154.0
2,2,COMMERCE,-.4760,6910 (NEW),37307 (NEW),2020,ECONOMICS,S,BUSINESS STUDIES,S,ACCOUNTING,S,050,S,new,16,August,2001,female,6910.0
3,3,COMMERCE,-.1012,5678 (NEW),30449 (NEW),2020,ECONOMICS,C,BUSINESS STUDIES,C,ACCOUNTING,S,034,S,new,16,August,2001,female,5678.0
4,4,COMMERCE,.6014,3269 (NEW),17010 (NEW),2020,ECONOMICS,C,BUSINESS STUDIES,C,ACCOUNTING,B,036,S,new,7,August,2000,female,3269.0

In [20]:
# Colab eke lassanata tables pennanna meka danna
from google.colab import data_table
data_table.enable_dataframe_formatter()

# Filter karapu table eka pennanna (head() noda methana meka witharak danna)
df_filtered_rank

Warning: total number of rows (70649) exceeds max_rows (20000). Falling back to pandas display.

,index,stream,Zscore,district_rank,island_rank,al_year,sub1,sub1_r,sub2,sub2_r,sub3,sub3_r,cgt_r,ge_r,syllabus,birth_day,birth_month,birth_year,gender,district_rank_numeric
49,49,ARTS,1.9997,108 (NEW),588 (NEW),2020,ECONOMICS,A,POLITICAL SCIENCE,A,ISLAM,A,062,A,new,3,February,2001,female,108.0
139,139,COMMERCE,1.8182,373 (NEW),1246 (NEW),2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,046,B,new,24,July,2001,male,373.0
185,185,COMMERCE,1.7950,412 (NEW),1370 (NEW),2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,050,C,new,17,December,2001,male,412.0
188,188,PHYSICAL SCIENCE,2.0254,259 (NEW),922 (NEW),2020,PHYSICS,B,CHEMISTRY,A,COMBINED MATHEMATICS,A,078,B,new,30,January,2002,male,259.0
199,199,PHYSICAL SCIENCE,1.7636,419 (NEW),1805 (NEW),2020,PHYSICS,A,CHEMISTRY,A,COMBINED MATHEMATICS,B,068,A,new,9,November,2001,male,419.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337546,337546,BIOLOGICAL SCIENCE,-.0393,74 (OLD),4417 (OLD),2020,PHYSICS,S,CHEMISTRY,S,BIOLOGY,C,058,F,old,21,September,1999,male,74.0
337547,337547,ARTS,-.0586,140 (OLD),4438 (OLD),2020,AGRICULTURAL SCIENCE,S,POLITICAL SCIENCE,S,COMMUNICATION & MEDIA STUDIES,C,043,C,old,22,August,1995,male,140.0
337549,337549,ARTS,-.3467,184 (OLD),5184 (OLD),2020,HOME ECONOMICS,B,CHRISTIANITY,B,DRAMA AND THEATRE (TAMIL),S,Absent,Absent,old,25,March,1997,female,184.0
337551,337551,BIOSYSTEMS TECHNOLOGY,.0509,24 (OLD),366 (OLD),2020,AGRICULTURAL SCIENCE,C,BIO SYSTEMS TECHNOLOGY,S,SCIENCE FOR TECHNOLOGY,S,Absent,Absent,old,3,September,1996,female,24.0
337552,337552,ARTS,-.1560,152 (OLD),4693 (OLD),2020,HOME ECONOMICS,B,COMMUNICATION & MEDIA STUDIES,S,ISLAM,C,030,Absent,old,27,April,1994,male,152.0

In [23]:
# 3 As gaththa lamai filter kirima
top_students = df_cleaned[(df_cleaned['sub1_r'] == 'A') &
                          (df_cleaned['sub2_r'] == 'A') &
                          (df_cleaned['sub3_r'] == 'A')]

print("Vishayayan 3tama 'A' gaththa lamai gaana:", top_students.shape[0])
display(top_students.head())

Vishayayan 3tama 'A' gaththa lamai gaana: 7685

,index,stream,Zscore,district_rank,island_rank,al_year,sub1,sub1_r,sub2,sub2_r,sub3,sub3_r,cgt_r,ge_r,syllabus,birth_day,birth_month,birth_year,gender,district_rank_numeric
49,49,ARTS,1.9997,108 (NEW),588 (NEW),2020,ECONOMICS,A,POLITICAL SCIENCE,A,ISLAM,A,062,A,new,3,February,2001,female,108.0
54,54,ARTS,1.4195,585 (NEW),6563 (NEW),2020,ECONOMICS,A,POLITICAL SCIENCE,A,ISLAM,A,038,B,new,20,July,2001,female,585.0
139,139,COMMERCE,1.8182,373 (NEW),1246 (NEW),2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,046,B,new,24,July,2001,male,373.0
166,166,COMMERCE,1.6087,717 (NEW),2713 (NEW),2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,064,B,new,26,July,2001,male,717.0
185,185,COMMERCE,1.7950,412 (NEW),1370 (NEW),2020,ECONOMICS,A,BUSINESS STUDIES,A,ACCOUNTING,A,050,C,new,17,December,2001,male,412.0

In [24]:
# District Rank eka 1 wechcha aya
district_first = df_cleaned[df_cleaned['district_rank_numeric'] == 1]

print("District 1st wechcha lamai gaana:", district_first.shape[0])
display(district_first)

District 1st wechcha lamai gaana: 267

,index,stream,Zscore,district_rank,island_rank,al_year,sub1,sub1_r,sub2,sub2_r,sub3,sub3_r,cgt_r,ge_r,syllabus,birth_day,birth_month,birth_year,gender,district_rank_numeric
2735,2735,PHYSICAL SCIENCE,2.9205,1 (NEW),3 (NEW),2020,PHYSICS,A,CHEMISTRY,A,COMBINED MATHEMATICS,A,076,A,new,8,June,2001,female,1.0
9891,9891,BIOLOGICAL SCIENCE,3.3182,1 (NEW),1 (NEW),2020,PHYSICS,A,CHEMISTRY,A,BIOLOGY,A,076,A,new,25,October,2001,male,1.0
13552,13552,COMMERCE,2.6124,1 (NEW),2 (NEW),2020,INFORMATION & COMMUNICATION TECHNOLOGY,A,ECONOMICS,A,ACCOUNTING,A,060,A,new,31,January,2002,female,1.0
26902,26902,ARTS,2.8319,1 (NEW),1 (NEW),2020,POLITICAL SCIENCE,A,HOME ECONOMICS,A,COMMUNICATION & MEDIA STUDIES,A,030,C,new,29,June,2001,female,1.0
30696,30696,ENGINEERING TECHNOLOGY,3.2199,1 (NEW),4 (NEW),2020,INFORMATION & COMMUNICATION TECHNOLOGY,A,ENGINEERING TECHNOLOGY,A,SCIENCE FOR TECHNOLOGY,A,070,A,new,26,April,2001,male,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336842,336842,BIOLOGICAL SCIENCE,2.0475,1 (OLD),101 (OLD),2020,PHYSICS,A,CHEMISTRY,A,BIOLOGY,A,050,F,old,28,October,1999,male,1.0
337083,337083,BIOSYSTEMS TECHNOLOGY,1.6039,1 (OLD),17 (OLD),2020,AGRICULTURAL SCIENCE,B,BIO SYSTEMS TECHNOLOGY,C,SCIENCE FOR TECHNOLOGY,B,052,F,old,28,July,1999,female,1.0
337220,337220,COMMERCE,1.5831,1 (OLD),103 (OLD),2020,AGRICULTURAL SCIENCE,B,BUSINESS STUDIES,B,ACCOUNTING,B,058,A,old,30,January,1999,male,1.0
337285,337285,PHYSICAL SCIENCE,1.8962,1 (OLD),35 (OLD),2020,PHYSICS,B,CHEMISTRY,A,COMBINED MATHEMATICS,A,075,A,old,28,October,1998,male,1.0
337334,337334,ARTS,1.8680,1 (OLD),33 (OLD),2020,POLITICAL SCIENCE,B,ISLAM,A,ARABIC,A,045,C,old,24,November,1999,female,1.0

In [26]:
# Stream eka SCIENCE saha Z-score eka 2.0 ta wadi aya

# Convert 'Zscore' column to numeric, coercing errors to NaN
df_cleaned['Zscore'] = pd.to_numeric(df_cleaned['Zscore'], errors='coerce')

# Filter out any NaN values that resulted from conversion errors if necessary (optional here as comparison will handle them)
high_zscore_science = df_cleaned[(df_cleaned['stream'] == 'SCIENCE') & (df_cleaned['Zscore'] > 2.0)]

print("Science eken Z-Score 2.0 ta wadi lamai gaana:", high_zscore_science.shape[0])
display(high_zscore_science.head())

Science eken Z-Score 2.0 ta wadi lamai gaana: 0

Empty DataFrame
Columns: [index, stream, Zscore, district_rank, island_rank, al_year, sub1, sub1_r, sub2, sub2_r, sub3, sub3_r, cgt_r, ge_r, syllabus, birth_day, birth_month, birth_year, gender, district_rank_numeric]
Index: []

In [27]:
# General English walata 'A', habai vishayayan thunatama 'F' gaththa lamai
english_pro_but_failed = df_cleaned[(df_cleaned['ge_r'] == 'A') &
                                    (df_cleaned['sub1_r'] == 'F') &
                                    (df_cleaned['sub2_r'] == 'F') &
                                    (df_cleaned['sub3_r'] == 'F')]

print("General English walata A thiyena, habai AL fail lamai gaana:", english_pro_but_failed.shape[0])
display(english_pro_but_failed.head())

General English walata A thiyena, habai AL fail lamai gaana: 1044

,index,stream,Zscore,district_rank,island_rank,al_year,sub1,sub1_r,sub2,sub2_r,sub3,sub3_r,cgt_r,ge_r,syllabus,birth_day,birth_month,birth_year,gender,district_rank_numeric
203,203,-,NaN,-,-,2020,PHYSICS,F,CHEMISTRY,F,BIOLOGY,F,052,A,new,20,March,2001,male,NaN
289,289,-,NaN,-,-,2020,PHYSICS,F,CHEMISTRY,F,COMBINED MATHEMATICS,F,044,A,new,10,September,1999,male,NaN
423,423,-,NaN,-,-,2020,PHYSICS,F,CHEMISTRY,F,COMBINED MATHEMATICS,F,032,A,new,15,April,2000,male,NaN
593,593,-,NaN,-,-,2020,PHYSICS,F,CHEMISTRY,F,COMBINED MATHEMATICS,F,044,A,new,19,July,2001,female,NaN
660,660,-,NaN,-,-,2020,PHYSICS,F,CHEMISTRY,F,BIOLOGY,F,Absent,A,new,27,July,2000,female,NaN

In [5]:
import pandas as pd

def extract_rank(rank_str):
    """Extracts the numerical part from the district_rank string."""
    if isinstance(rank_str, str):
        try:
            return int(rank_str.split(' ')[0])
        except ValueError:
            return None
    return None

def transform_data(input_file_path, output_file_path):
    print(f"Loading data from {input_file_path}...")
    df = pd.read_csv(input_file_path)

    print("Initial Data Shape:", df.shape)

    # 1. Drop missing values in specific columns (e.g., gender)
    print("Dropping rows with missing gender...")
    df_cleaned = df.dropna(subset=['gender']).copy()

    # 2. Drop duplicate rows
    print("Dropping duplicate rows...")
    df_cleaned = df_cleaned.drop_duplicates().copy()

    # 3. Extract numerical district rank
    print("Extracting numerical district ranks...")
    df_cleaned['district_rank_numeric'] = df_cleaned['district_rank'].apply(extract_rank)

    print("Final Data Shape after transformations:", df_cleaned.shape)

    # Save the transformed dataset
    print(f"Saving transformed data to {output_file_path}...")
    df_cleaned.to_csv(output_file_path, index=False)
    print("Transformation complete! 🚀")

if __name__ == "__main__":
    # Define file paths (Change these if running in Colab/Drive)
    INPUT_FILE = "/content/2020_al_data_kaggle_upload_new_old_syllabi.csv"
    OUTPUT_FILE = "cleaned_al_data.csv"

    transform_data(INPUT_FILE, OUTPUT_FILE)

Loading data from /content/2020_al_data_kaggle_upload_new_old_syllabi.csv...
Initial Data Shape: (337553, 19)
Dropping rows with missing gender...
Dropping duplicate rows...
Extracting numerical district ranks...
Final Data Shape after transformations: (336069, 20)
Saving transformed data to cleaned_al_data.csv...
Transformation complete! 🚀

In [9]:
import pandas as pd

# Load the cleaned data into df_cleaned
df_cleaned = pd.read_csv('/content/cleaned_al_data.csv')

print('df_cleaned DataFrame successfully load')
print(df_cleaned.shape)

df_cleaned DataFrame successfully load
(336069, 20)

In [4]:
from google.colab import files

print("'2020_al_data_kaggle_upload_new_old_syllabi.csv' ")
uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

කරුණාකර '2020_al_data_kaggle_upload_new_old_syllabi.csv' ගොනුව තෝරා උඩුගත කරන්න.

Saving 2020_al_data_kaggle_upload_new_old_syllabi.csv to 2020_al_data_kaggle_upload_new_old_syllabi.csv
User uploaded file "2020_al_data_kaggle_upload_new_old_syllabi.csv" with length 42295007 bytes